- name: shakePlate
  type: Action
  input:
  - { name: agent, type: Agent, mode: Plannable }
  - { name: device, type: Device, mode: Plannable }
  - { name: program, type: Program, mode: Required }
  - { name: plate, type: Labware, mode: Required }
  - { name: model, type: LabwareModel, mode: Plannable }
  - { name: site, type: Site, mode: Plannable }
  precond:
  - agent-has-device $agent $device
  - device-can-site $device $site
  - model $plate $model
  - location $plate $site
  output:
  - CALL: instruction
    INPUT:
      agent: agent
      command: ShakerRun
      device: device
      program: program
      labware: plate
      site: site

