(defproblem pa domain
 ; initial conditions
 (
  (is-plateModel m2)
  (is-site offsite)
  (is-agent user)
  (is-site s1)
  (is-site shakerSite)
  (is-transporter r1arm)
  (is-plate plate1)
  (is-site sealerSite)
  (is-site s2)
  (is-thermocycler thermocycler)
  (is-thermocyclerSpec thermocyclerSpec1)
  (is-transporter userArm)
  (is-pipetter pipetter)
  (is-siteModel siteModelAll)
  (is-siteModel siteModel1)
  (is-agent r1)
  (is-siteModel siteModel12)
  (is-site thermocyclerSite)
  (is-shaker shaker)
  (is-plateModel m1)
  (is-shakerSpec shakerSpec1)
  (is-sealer sealer)
  (agent-has-device user userArm)
  (agent-has-device r1 shaker)
  (agent-has-device r1 pipetter)
  (agent-has-device r1 r1arm)
  (agent-has-device r1 sealer)
  (agent-has-device r1 thermocycler)
  (device-can-model r1arm m1)
  (device-can-model r1arm m2)
  (device-can-model thermocycler m1)
  (device-can-model userArm m1)
  (device-can-model userArm m2)
  (device-can-model pipetter m1)
  (device-can-model pipetter m2)
  (device-can-model shaker m1)
  (device-can-model shaker m2)
  (device-can-model sealer m1)
  (device-can-site r1arm s1)
  (device-can-site r1arm s2)
  (device-can-site r1arm sealerSite)
  (device-can-site r1arm thermocyclerSite)
  (device-can-site thermocycler thermocyclerSite)
  (device-can-site userArm offsite)
  (device-can-site userArm s1)
  (device-can-site pipetter s1)
  (device-can-site pipetter s2)
  (device-can-site shaker shakerSite)
  (device-can-site sealer sealerSite)
  (device-can-spec thermocycler thermocyclerSpec1)
  (device-can-spec shaker shakerSpec1)
  (stackable siteModel1 m1)
  (stackable siteModelAll m1)
  (stackable siteModelAll m2)
  (stackable siteModel12 m1)
  (stackable siteModel12 m2)
  (model offsite siteModelAll)
  (model shakerSite siteModel12)
  (model s1 siteModel12)
  (model plate1 m1)
  (model sealerSite siteModel1)
  (model s2 siteModel12)
  (model thermocyclerSite siteModel1)
  (location plate1 sealerSite)
 )
 ;tasks
 (
  (sealer-run ?a0001 ?d0002 plate1 m1 ?s0003)
 )
)
