#plateModels:
#  "D-BSSE 96 Well PCR Plate":
#  "D-BSSE 96 Well DWP":
#  "D-BSSE 384 Well Plate White":
#  "Ellis Nunc F96 MicroWell":
#  "Trough 100ml":

evowareAgents:
  r1:
    evowareDir: testdata/bsse-robot1/config
    #tableFile: testdata/bsse-robot1/config/table-01.esc
    labware:
      - D-BSSE 96 Well PCR Plate
      - D-BSSE 96 Well DWP
      - D-BSSE 384 Well Plate White
      - Ellis Nunc F96 MicroWell
      - Trough 100ml

    tipModels:
      Standard 50ul: { min: 0.1, max: 45 }
      Standard 1000ul: { min: 3, max: 950 }

    tips:
      - { row: 1, permanentModel: Standard 1000ul }
      - { row: 2, permanentModel: Standard 1000ul }
      - { row: 3, permanentModel: Standard 1000ul }
      - { row: 4, permanentModel: Standard 1000ul }
      - { row: 5, permanentModel: Standard 50ul }
      - { row: 6, permanentModel: Standard 50ul }
      - { row: 7, permanentModel: Standard 50ul }
      - { row: 8, permanentModel: Standard 50ul }

    tableSetups:
      default:
        tableFile: testdata/bsse-robot1/config/table-01.esc
        sites:
          P1: { grid: 9, site: 3 }
          P2: { grid: 10, site: 2 }
          P3: { grid: 10, site: 4 }
          R1A: { grid: 3, site: 1 }
          R1B: { grid: 3, site: 2 }
          R1C: { grid: 3, site: 3 }
          ROBOSEAL: { carrier: "RoboSeal" }
#          T1A: { grid: 5
        pipetterSites: [P1, P2, P3, R1A, R1B, R1C]
        userSites: [P1, P2, P3, R1A, R1B, R1C]

aliases:
  Thermocycler Plate: D-BSSE 96 Well PCR Plate
  "384 Well Plate": D-BSSE 384 Well Plate White
  PA3P: r1_bench_017x1
  PA1: r1_bench_009x3
  PB1: r1_bench_010x2
  PC1: r1_bench_010x4

logic:
#  - transporter-can userArm r1_hotel_245x1 userArmSpec
#  - transporter-can userArm r1_hotel_245x2 userArmSpec
#  - transporter-can userArm r1_bench_003x1 userArmSpec
#  - transporter-can userArm r1_bench_003x2 userArmSpec
#  - transporter-can userArm r1_bench_003x3 userArmSpec
#  - transporter-can userArm r1_bench_010x2 userArmSpec
#  - device-can-site r1_pipetter1 r1_bench_010x1
  - device-can-site r1_pipetter1 r1_bench_010x2
  - device-can-site r1_pipetter1 r1_bench_010x4
  - device-can-site r1_pipetter1 r1_bench_017x1
  - device-can-site r1_pipetter1 r1_bench_017x2
  - device-can-site r1_pipetter1 r1_bench_017x3
  - device-can-site r1_pipetter1 r1_bench_017x4

specs:
  peelerSpec1: C:\Programme\HJBioanalytikGmbH\RoboPeel3\RoboPeel_PlateParameters\4titude_PCR_blue.bcf
  sealerSpec1: C:\Programme\HJBioanalytikGmbH\RoboSeal3\RoboSeal_PlateParameters\4titude_PCR_red.bcf
  #shakerSpec1: "60"
  thermocyclerSpec1: "1.0"

deviceToSpec:
  - [r1_thermocycler1, thermocyclerSpec1]
  #- [r1_shaker, shakerSpec1]

deviceToModelToSpec:
  - [r1_sealer, "D-BSSE 96 Well PCR Plate", sealerSpec1]
  - [r1_peeler, "D-BSSE 96 Well PCR Plate", peelerSpec1]

