# Temporary file for more conveniently compiling several scripts

luigi_protocol2:
	npm start -- --no-ourlab src/config/ourlab_luigi.js protocols/luigi_protocol2.yaml && npm run evoware -- ../testdata/bsse-luigi/Carrier.cfg ../testdata/bsse-luigi/DM_WorkTable_June2015.ewt protocols/luigi_protocol2.out.json ourlab.luigi.evoware

growthcurve02_testing:
	npm start -- --no-ourlab src/config/ourlab_luigi.js protocols/growthcurve02_testing.yaml && npm run evoware -- ../testdata/bsse-luigi/Carrier.cfg ../testdata/bsse-luigi/Roboliq_Standard_20160311.ewt protocols/growthcurve02_testing.out.json ourlab.luigi.evoware

growthcurve03_testing:
	npm start -- --no-ourlab src/config/ourlab_luigi.js protocols/growthcurve03_testing.yaml && npm run evoware -- ../testdata/bsse-luigi/Carrier.cfg ../testdata/bsse-luigi/Roboliq_Standard_20160311.ewt protocols/growthcurve03_testing.out.json ourlab.luigi.evoware
