(define (problem pb8)
	(:domain travel)
	(:requirements :strips :equality)
  	(:objects a g jack bulldozer)
  	(:init (at jack a) (at bulldozer a)
	 	(vehicle bulldozer)
	 	(mobile jack)
		(person jack)
	 	(road a g) (road g a))
	(:goal (and (at bulldozer g) (at Jack a)))
)