(define (problem pb5)
	(:domain travel)
	(:requirements :strips :equality)
  	(:objects a g jack bulldozer)
  	(:init (at jack a) (at bulldozer a)
		(vehicle bulldozer)
	 	(mobile jack)
		(person jack)
	 	(road a g))
 	(:goal (and (at bulldozer g))) 
  )